add initializer_list mock for testing
Ericsson/clang pull request #405
Opened 2018-06-07 06:06 UTC by gyorb

if STL is missing on the host machine the tests
will not run without a mock

2018-06-07 06:08 UTC, gyorb commented
Should I remove the `-std=c++11` argument from the test compilation commands?
`clang++ -x c++-header -std=c++11 -o ...` and
`clang_cc1 -x c++ -std=c++11 -ast-merge ...`

2018-06-07 07:52 UTC, gerazo commented
How can STL be missing? I assume that running clang-sa needs a full clang installed which in fact brings its own library implementations which should include STL. Is there a finer grain package structure in which it is not happening?

2018-06-07 08:10 UTC, balazske commented
If <initializer_list> is not used we can use the "usual" way of test.cpp:
```
// RUN: %clang_cc1 -emit-pch -o %t.1.ast %S/Inputs/il.cpp
// RUN: %clang_cc1 -ast-merge %t.1.ast -fsyntax-only %s 2>&1 | FileCheck --allow-empty %s
// CHECK-NOT: unsupported AST node
```

2018-06-07 08:33 UTC, balazske requested changes
Modify test.cpp (see my previous comment).

2018-06-07 10:21 UTC, gyorb commented
@balazske I've done the changes.

2018-06-07 10:24 UTC, balazske approved these changes

2018-06-07 10:31 UTC, dkrupp approved these changes
LGTM

2018-06-07 10:31 UTC, merged

2018-06-18 12:50 UTC, martong commented
@gerazo 
> How can STL be missing? I assume that running clang-sa needs a full clang installed which in fact brings its own library implementations which should include STL. Is there a finer grain package structure in which it is not happening?

When you use Clang on Linux, the default STL is coming from libstdc++ from the first available GCC. Setting up libc++ on Linux (the llvm.org STL implementation) is possible, but requires additional , non-default and non-trivial steps.
In this case I think there is an STL in linstdc++ but the <initializer_list> header is missing, older GCC/libstdc++ didn't have that.