[WIP]Add analyzer option to limit the number of TUs imported
Ericsson/clang pull request #619
Opened 2019-02-25 09:24 UTC by gamesh411

2019-02-26 08:45 UTC, martong reviewed
You have so many unrelated changes which seems like the result of an automated formatting. Could you please avoid them?
You may use `git clang-format` which formats only the changed lines.

2019-02-26 08:45 UTC, martong commented on lib/StaticAnalyzer/Core/AnalyzerOptions.cpp
> +                   .Case("shallow", UMK_Shallow)
Is this change related?

2019-02-26 10:19 UTC, martong approved these changes
Looks good!

2019-02-26 12:00 UTC, gamesh411 commented
I have run into a dependency issue. If I store the TU threshold as an AnalyzerOption, then I have to link with libStaticAnalyzerCore (see CMakeLists.txt change). But this introduces a cyclic dependency. I see a couple of solutions to this problem:

a) put the option elsewhere, for example as a general frontend-option
b) make the check elsewhere, for example inside some analyzer-specific manager class
c) try to cut the dependency by introducing intermediary libs

What are your thoughts?

2019-02-26 12:08 UTC, martong commented
> I have run into a dependency issue. If I store the TU threshold as an AnalyzerOption, then I have to link with libStaticAnalyzerCore (see CMakeLists.txt change). But this introduces a cyclic dependency. I see a couple of solutions to this problem:
> 
> a) put the option elsewhere, for example as a general frontend-option
> b) make the check elsewhere, for example inside some analyzer-specific manager class
> c) try to cut the dependency by introducing intermediary libs
> 
> What are your thoughts?

I prefer option a). Because CrossTU is ought to be independent from the analyzer, that is more generic.

2019-02-27 10:01 UTC, martong approved these changes
Looks good!

2019-03-11 09:24 UTC, Szelethus commented
Shouldn't this be an analyzer config option instead? I am aware of several CTU options that are just that, why is this a frontend option?

2019-03-11 09:28 UTC, martong commented
> Shouldn't this be an analyzer config option instead? I am aware of several CTU options that are just that, why is this a frontend option?

Yes this should be an analyzer option, but the first attempt somehow created a lib  dependency failure.
So, Endre is working on the second attempt where he will extend the parameters of `CrossTranslationUnitContext::getCrossTUDefinition` like we do with `DisplayCTUProgress`.

2019-03-11 09:29 UTC, martong requested changes
Please extend the parameters of CrossTranslationUnitContext::getCrossTUDefinition like we do with DisplayCTUProgress.

2019-03-12 06:42 UTC, Szelethus commented
> > Shouldn't this be an analyzer config option instead? I am aware of several CTU options that are just that, why is this a frontend option?
> 
> Yes this should be an analyzer option, but the first attempt somehow created a lib dependency failure.
The reason probably was that my analyzer config changes are not live on clang7 -- the solution would be to leave the option's getter method in-class, I believe.

2019-03-14 10:38 UTC, dkrupp commented
deadline for this is 31st of March!

2019-03-20 09:34 UTC, gamesh411 commented
Reorganized parameter handling, added unit test, and some documentation.

2019-03-20 11:06 UTC, Szelethus commented
Sorry for missing out on the discussion. I think adding this as an analyzer-config flag WOULD be preferred on clang 8.0.0, but since we can't list and verify these options in 7.0.0., let's not shoot ourselves in the foot with them.

LGTM regarding option placement, I can't say much about the rest of the patch.

2019-03-20 16:44 UTC, martong approved these changes
LG! Nice work!

2019-03-20 16:44 UTC, martong commented on include/clang/StaticAnalyzer/Core/AnalyzerOptions.h
> +  unsigned CTUImportThreshold{100u};
I am not sure that aggregate initialization will be compiled without problems on GCC 4.8. Clang master still supports that compiler with C++11, right?
Perhaps ` = 100u;` would be more appropriate.

2019-03-21 10:29 UTC, merged